apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_MANAGEMENT_PORT: "15672"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-worker-config
data:
  ASPNETCORE_ENVIRONMENT: Production